/**
 * Numbered certificate-course structure (matches JavaScript pattern).
 * Used by seed-numbered-curriculum.js
 */

const MODULES = [
  { id: "00-certification", label: "Certification", lessons: 3 },
  { id: "01-beginner", label: "Beginner", lessons: 10 },
  { id: "02-intermediate", label: "Intermediate", lessons: 6 },
  { id: "03-advanced", label: "Advanced", lessons: 7 },
  { id: "04-professional", label: "Professional", lessons: 6 },
  { id: "05-mastery", label: "Mastery", lessons: 4 },
];

const CERT_LESSONS = [
  { num: "00", slug: "roadmap", title: "Course Roadmap" },
  { num: "01", slug: "certificate-requirements", title: "Certificate Requirements" },
  { num: "02", slug: "final-assessment", title: "Final Assessment" },
];

/** Per-language beginner → mastery lesson slugs and titles */
const LANGUAGE_LESSONS = {
  Python: {
    "01-beginner": [
      ["introduction", "Introduction to Python"],
      ["python-basics", "Python Basics and Syntax"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Data Types"],
      ["control-flow-and-loops", "Control Flow and Loops"],
      ["functions-basics", "Functions"],
      ["lists-and-tuples", "Lists and Tuples"],
      ["dictionaries-and-sets", "Dictionaries and Sets"],
      ["strings-and-formatting", "Strings and Formatting"],
      ["file-io-basics", "File I/O Basics"],
    ],
    "02-intermediate": [
      ["comprehensions", "List Comprehensions"],
      ["error-handling", "Error Handling"],
      ["modules-and-packages", "Modules and Packages"],
      ["oop-basics", "Object-Oriented Programming"],
      ["virtual-environments", "Virtual Environments and pip"],
      ["working-with-json", "JSON and APIs"],
    ],
    "03-advanced": [
      ["decorators", "Decorators"],
      ["generators", "Generators and Iterators"],
      ["context-managers", "Context Managers"],
      ["type-hints", "Type Hints"],
      ["async-basics", "Async Programming Basics"],
      ["testing-with-pytest", "Testing with pytest"],
      ["performance-tips", "Performance Tips"],
    ],
    "04-professional": [
      ["flask-basics", "Flask Web Basics"],
      ["fastapi-intro", "FastAPI Introduction"],
      ["database-sqlite", "SQLite and Databases"],
      ["data-analysis-pandas", "Data Analysis with Pandas"],
      ["deployment-basics", "Deployment Basics"],
      ["project-structure", "Professional Project Structure"],
    ],
    "05-mastery": [
      ["algorithms", "Algorithms in Python"],
      ["data-structures", "Data Structures"],
      ["capstone-projects", "Capstone Projects"],
      ["production-checklist", "Production Readiness Checklist"],
    ],
  },
  Java: {
    "01-beginner": [
      ["introduction", "Introduction to Java"],
      ["java-basics", "Java Basics and Syntax"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Data Types"],
      ["control-flow-and-loops", "Control Flow and Loops"],
      ["methods-basics", "Methods"],
      ["arrays", "Arrays"],
      ["classes-intro", "Classes Introduction"],
      ["strings", "Strings"],
      ["scanner-input", "User Input with Scanner"],
    ],
    "02-intermediate": [
      ["oop-inheritance", "Inheritance and Polymorphism"],
      ["interfaces", "Interfaces and Abstract Classes"],
      ["collections", "Collections Framework"],
      ["exceptions", "Exception Handling"],
      ["generics-intro", "Generics Introduction"],
      ["file-io", "File I/O"],
    ],
    "03-advanced": [
      ["streams-api", "Streams API"],
      ["multithreading", "Multithreading Basics"],
      ["lambdas", "Lambda Expressions"],
      ["jdbc-basics", "JDBC and Databases"],
      ["unit-testing-junit", "JUnit Testing"],
      ["design-patterns", "Design Patterns Intro"],
      ["jvm-and-memory", "JVM and Memory"],
    ],
    "04-professional": [
      ["spring-boot-intro", "Spring Boot Introduction"],
      ["rest-apis", "Building REST APIs"],
      ["maven-gradle", "Maven and Gradle"],
      ["logging", "Logging Best Practices"],
      ["security-basics", "Security Basics"],
      ["microservices-intro", "Microservices Introduction"],
    ],
    "05-mastery": [
      ["algorithms", "Algorithms in Java"],
      ["data-structures", "Data Structures"],
      ["capstone-projects", "Capstone Projects"],
      ["interview-prep", "Interview Preparation"],
    ],
  },
  "C++": {
    "01-beginner": [
      ["introduction", "Introduction to C++"],
      ["cpp-basics", "C++ Basics"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Types"],
      ["control-flow", "Control Flow"],
      ["functions", "Functions"],
      ["arrays-and-strings", "Arrays and Strings"],
      ["pointers-intro", "Pointers Introduction"],
      ["references", "References"],
      ["iostream", "Input and Output"],
    ],
    "02-intermediate": [
      ["classes-and-objects", "Classes and Objects"],
      ["constructors", "Constructors and Destructors"],
      ["inheritance", "Inheritance"],
      ["polymorphism", "Polymorphism"],
      ["templates-intro", "Templates Introduction"],
      ["stl-containers", "STL Containers"],
    ],
    "03-advanced": [
      ["smart-pointers", "Smart Pointers"],
      ["move-semantics", "Move Semantics"],
      ["operator-overloading", "Operator Overloading"],
      ["exception-handling", "Exception Handling"],
      ["file-io", "File I/O"],
      ["multithreading", "Multithreading"],
      ["modern-cpp", "Modern C++ Features"],
    ],
    "04-professional": [
      ["cmake-basics", "CMake Basics"],
      ["debugging-gdb", "Debugging with GDB"],
      ["performance", "Performance Optimization"],
      ["networking-basics", "Networking Basics"],
      ["game-dev-intro", "Game Development Intro"],
      ["embedded-intro", "Embedded Systems Intro"],
    ],
    "05-mastery": [
      ["algorithms", "Algorithms in C++"],
      ["data-structures", "Data Structures"],
      ["capstone-projects", "Capstone Projects"],
      ["systems-design", "Systems Design"],
    ],
  },
  C: {
    "01-beginner": [
      ["introduction", "Introduction to C"],
      ["c-basics", "C Basics"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Types"],
      ["control-flow", "Control Flow"],
      ["functions", "Functions"],
      ["arrays", "Arrays"],
      ["pointers-intro", "Pointers Introduction"],
      ["strings", "Strings"],
      ["structs", "Structures"],
    ],
    "02-intermediate": [
      ["dynamic-memory", "Dynamic Memory"],
      ["file-io", "File I/O"],
      ["function-pointers", "Function Pointers"],
      ["preprocessor", "Preprocessor"],
      ["bitwise-ops", "Bitwise Operations"],
      ["linked-lists", "Linked Lists"],
    ],
    "03-advanced": [
      ["data-structures", "Data Structures in C"],
      ["algorithms", "Algorithms in C"],
      ["networking-sockets", "Sockets Introduction"],
      ["multithreading-pthreads", "POSIX Threads"],
      ["debugging", "Debugging C Programs"],
      ["embedded-c", "Embedded C"],
      ["portability", "Portability and Standards"],
    ],
    "04-professional": [
      ["makefiles", "Makefiles"],
      ["libraries", "Building Libraries"],
      ["systems-programming", "Systems Programming"],
      ["security-c", "Secure C Coding"],
      ["linux-apis", "Linux APIs"],
      ["performance", "Performance Tuning"],
    ],
    "05-mastery": [
      ["algorithms", "Advanced Algorithms"],
      ["os-concepts", "OS Concepts"],
      ["capstone-projects", "Capstone Projects"],
      ["career-path", "Career Path"],
    ],
  },
  "C#": {
    "01-beginner": [
      ["introduction", "Introduction to C#"],
      ["csharp-basics", "C# Basics"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Types"],
      ["control-flow", "Control Flow"],
      ["methods", "Methods"],
      ["arrays", "Arrays"],
      ["classes-intro", "Classes Introduction"],
      ["strings", "Strings"],
      ["collections-intro", "Collections Introduction"],
    ],
    "02-intermediate": [
      ["oop-inheritance", "Inheritance"],
      ["interfaces", "Interfaces"],
      ["linq-basics", "LINQ Basics"],
      ["exceptions", "Exception Handling"],
      ["generics", "Generics"],
      ["async-await", "Async and Await"],
    ],
    "03-advanced": [
      ["delegates-events", "Delegates and Events"],
      ["reflection", "Reflection"],
      ["memory-management", "Memory Management"],
      ["unit-testing", "Unit Testing"],
      ["design-patterns", "Design Patterns"],
      ["aspnet-core-intro", "ASP.NET Core Intro"],
      ["entity-framework", "Entity Framework Intro"],
    ],
    "04-professional": [
      ["web-apis", "Building Web APIs"],
      ["blazor-intro", "Blazor Introduction"],
      ["dependency-injection", "Dependency Injection"],
      ["logging", "Logging"],
      ["azure-basics", "Azure Basics"],
      ["ci-cd", "CI/CD for .NET"],
    ],
    "05-mastery": [
      ["algorithms", "Algorithms in C#"],
      ["data-structures", "Data Structures"],
      ["capstone-projects", "Capstone Projects"],
      ["architecture", "Software Architecture"],
    ],
  },
  Go: {
    "01-beginner": [
      ["introduction", "Introduction to Go"],
      ["go-basics", "Go Basics"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Types"],
      ["control-flow", "Control Flow"],
      ["functions", "Functions"],
      ["arrays-and-slices", "Arrays and Slices"],
      ["maps", "Maps"],
      ["structs", "Structs"],
      ["packages", "Packages and Imports"],
    ],
    "02-intermediate": [
      ["methods", "Methods and Receivers"],
      ["interfaces", "Interfaces"],
      ["error-handling", "Error Handling"],
      ["goroutines", "Goroutines"],
      ["channels", "Channels"],
      ["testing", "Testing in Go"],
    ],
    "03-advanced": [
      ["context", "Context Package"],
      ["http-servers", "HTTP Servers"],
      ["json-encoding", "JSON Encoding"],
      ["modules", "Go Modules"],
      ["profiling", "Profiling"],
      ["concurrency-patterns", "Concurrency Patterns"],
      ["security", "Security Best Practices"],
    ],
    "04-professional": [
      ["rest-apis", "REST APIs in Go"],
      ["databases", "Databases with Go"],
      ["docker", "Dockerizing Go Apps"],
      ["grpc-intro", "gRPC Introduction"],
      ["microservices", "Microservices"],
      ["deployment", "Deployment"],
    ],
    "05-mastery": [
      ["algorithms", "Algorithms in Go"],
      ["data-structures", "Data Structures"],
      ["capstone-projects", "Capstone Projects"],
      ["open-source", "Contributing to Open Source"],
    ],
  },
  PHP: {
    "01-beginner": [
      ["introduction", "Introduction to PHP"],
      ["php-basics", "PHP Basics"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Types"],
      ["control-flow", "Control Flow"],
      ["functions", "Functions"],
      ["arrays", "Arrays"],
      ["strings", "Strings"],
      ["forms", "HTML Forms"],
      ["includes", "Includes and Requires"],
    ],
    "02-intermediate": [
      ["oop-basics", "OOP in PHP"],
      ["namespaces", "Namespaces"],
      ["error-handling", "Error Handling"],
      ["sessions-cookies", "Sessions and Cookies"],
      ["pdo-databases", "PDO and Databases"],
      ["composer", "Composer Package Manager"],
    ],
    "03-advanced": [
      ["mvc-pattern", "MVC Pattern"],
      ["security", "PHP Security"],
      ["rest-apis", "REST APIs"],
      ["testing-phpunit", "PHPUnit Testing"],
      ["performance", "Performance"],
      ["psr-standards", "PSR Standards"],
      ["laravel-intro", "Laravel Introduction"],
    ],
    "04-professional": [
      ["laravel-routing", "Laravel Routing"],
      ["eloquent-orm", "Eloquent ORM"],
      ["authentication", "Authentication"],
      ["deployment", "Deployment"],
      ["api-development", "API Development"],
      ["devops-php", "DevOps for PHP"],
    ],
    "05-mastery": [
      ["algorithms", "Algorithms in PHP"],
      ["data-structures", "Data Structures"],
      ["capstone-projects", "Capstone Projects"],
      ["freelance-guide", "Freelance and Career Guide"],
    ],
  },
  Ruby: {
    "01-beginner": [
      ["introduction", "Introduction to Ruby"],
      ["ruby-basics", "Ruby Basics"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Types"],
      ["control-flow", "Control Flow"],
      ["methods", "Methods"],
      ["arrays", "Arrays"],
      ["hashes", "Hashes"],
      ["blocks", "Blocks"],
      ["symbols", "Symbols"],
    ],
    "02-intermediate": [
      ["classes", "Classes and Objects"],
      ["modules", "Modules and Mixins"],
      ["exceptions", "Exception Handling"],
      ["file-io", "File I/O"],
      ["gems", "RubyGems"],
      ["testing-rspec", "Testing with RSpec"],
    ],
    "03-advanced": [
      ["metaprogramming", "Metaprogramming"],
      ["rails-intro", "Ruby on Rails Intro"],
      ["activerecord", "ActiveRecord"],
      ["routing", "Rails Routing"],
      ["background-jobs", "Background Jobs"],
      ["security", "Security in Rails"],
      ["performance", "Performance"],
    ],
    "04-professional": [
      ["rest-apis-rails", "REST APIs with Rails"],
      ["authentication-devise", "Authentication"],
      ["deployment", "Deployment"],
      ["api-only", "API-Only Rails"],
      ["testing-rails", "Testing Rails Apps"],
      ["hotwire", "Hotwire and Turbo"],
    ],
    "05-mastery": [
      ["algorithms", "Algorithms in Ruby"],
      ["data-structures", "Data Structures"],
      ["capstone-projects", "Capstone Projects"],
      ["open-source", "Open Source Ruby"],
    ],
  },
  Rust: {
    "01-beginner": [
      ["introduction", "Introduction to Rust"],
      ["rust-basics", "Rust Basics"],
      ["hello-world", "Hello World"],
      ["variables-and-types", "Variables and Types"],
      ["control-flow", "Control Flow"],
      ["functions", "Functions"],
      ["ownership", "Ownership Basics"],
      ["borrowing", "Borrowing and References"],
      ["structs", "Structs"],
      ["enums", "Enums and Pattern Matching"],
    ],
    "02-intermediate": [
      ["error-handling", "Error Handling with Result"],
      ["collections", "Collections"],
      ["traits", "Traits"],
      ["lifetimes", "Lifetimes"],
      ["modules", "Modules and Crates"],
      ["testing", "Testing in Rust"],
    ],
    "03-advanced": [
      ["smart-pointers", "Smart Pointers"],
      ["concurrency", "Concurrency"],
      ["async-rust", "Async Rust"],
      ["macros", "Macros"],
      ["unsafe-rust", "Unsafe Rust"],
      ["ffi", "Foreign Function Interface"],
      ["performance", "Performance"],
    ],
    "04-professional": [
      ["cli-apps", "CLI Applications"],
      ["web-axum", "Web with Axum"],
      ["databases", "Databases"],
      ["cargo-workspace", "Cargo Workspaces"],
      ["deployment", "Deployment"],
      ["embedded", "Embedded Rust"],
    ],
    "05-mastery": [
      ["algorithms", "Algorithms in Rust"],
      ["data-structures", "Data Structures"],
      ["capstone-projects", "Capstone Projects"],
      ["systems-programming", "Systems Programming"],
    ],
  },
  Quantum: {
    "01-beginner": [
      ["introduction", "Introduction to Quantum Computing"],
      ["qubits-basics", "Qubits and Superposition"],
      ["quantum-gates", "Quantum Gates"],
      ["measurement", "Measurement"],
      ["entanglement", "Entanglement"],
      ["bell-states", "Bell States"],
      ["quantum-circuits", "Quantum Circuits"],
      ["simulators", "Quantum Simulators"],
      ["linear-algebra", "Linear Algebra Refresher"],
      ["first-circuit", "Your First Circuit"],
    ],
    "02-intermediate": [
      ["deutsch-algorithm", "Deutsch Algorithm"],
      ["grover-intro", "Grover Search Intro"],
      ["quantum-teleportation", "Quantum Teleportation"],
      ["error-basics", "Quantum Error Basics"],
      ["density-matrices", "Density Matrices"],
      ["quantum-software", "Quantum Software Stack"],
    ],
    "03-advanced": [
      ["shor-intro", "Shor Algorithm Intro"],
      ["variational-algorithms", "Variational Algorithms"],
      ["qaoa", "QAOA"],
      ["noise-models", "Noise Models"],
      ["hardware", "Quantum Hardware"],
      ["hybrid-computing", "Hybrid Classical-Quantum"],
      ["research-frontiers", "Research Frontiers"],
    ],
    "04-professional": [
      ["qiskit-basics", "Qiskit Basics"],
      ["azure-quantum", "Azure Quantum"],
      ["braket", "AWS Braket"],
      ["optimization", "Quantum Optimization"],
      ["cryptography", "Post-Quantum Cryptography"],
      ["industry-use-cases", "Industry Use Cases"],
    ],
    "05-mastery": [
      ["algorithms-survey", "Quantum Algorithms Survey"],
      ["research-projects", "Research Projects"],
      ["capstone-projects", "Capstone Projects"],
      ["career-path", "Quantum Career Path"],
    ],
  },
  "Q#": {
    "01-beginner": [
      ["introduction", "Introduction to Q#"],
      ["quantum-concepts", "Quantum Concepts Review"],
      ["hello-quantum", "Hello Quantum World"],
      ["operations", "Q# Operations"],
      ["qubits", "Working with Qubits"],
      ["measurements", "Measurements in Q#"],
      ["functions", "Functions and UDTs"],
      ["control-flow", "Control Flow"],
      ["simulators", "Simulators"],
      ["first-algorithm", "First Quantum Algorithm"],
    ],
    "02-intermediate": [
      ["oracle-functions", "Oracle Functions"],
      ["amplitude-amplification", "Amplitude Amplification"],
      ["entanglement-qsharp", "Entanglement in Q#"],
      ["testing", "Testing Q# Programs"],
      ["interop-csharp", "C# Interop"],
      ["resource-estimation", "Resource Estimation"],
    ],
    "03-advanced": [
      ["deutsch-jozsa", "Deutsch-Jozsa"],
      ["grover", "Grover in Q#"],
      ["quantum-fft", "Quantum Fourier Transform"],
      ["error-correction", "Error Correction Intro"],
      ["azure-quantum", "Azure Quantum Workspace"],
      ["optimization", "Quantum Optimization"],
      ["advanced-patterns", "Advanced Patterns"],
    ],
    "04-professional": [
      ["production-workflows", "Production Workflows"],
      ["hybrid-apps", "Hybrid Applications"],
      ["performance", "Performance Tuning"],
      ["team-projects", "Team Projects"],
      ["documentation", "Documentation Standards"],
      ["deployment", "Deployment"],
    ],
    "05-mastery": [
      ["algorithm-design", "Algorithm Design"],
      ["research", "Research Topics"],
      ["capstone-projects", "Capstone Projects"],
      ["certification-prep", "Certification Prep"],
    ],
  },
  SQL: {
    "01-beginner": [
      ["introduction", "Introduction to SQL"],
      ["sql-basics", "SQL Basics"],
      ["select-queries", "SELECT Queries"],
      ["filtering", "WHERE and Filtering"],
      ["sorting", "ORDER BY"],
      ["aggregates", "Aggregate Functions"],
      ["joins-intro", "JOINs Introduction"],
      ["insert-update", "INSERT and UPDATE"],
      ["delete", "DELETE and Safety"],
      ["database-design", "Database Design Basics"],
    ],
    "02-intermediate": [
      ["subqueries", "Subqueries"],
      ["indexes", "Indexes"],
      ["views", "Views"],
      ["stored-procedures", "Stored Procedures"],
      ["transactions", "Transactions"],
      ["normalization", "Normalization"],
    ],
    "03-advanced": [
      ["window-functions", "Window Functions"],
      ["ctes", "Common Table Expressions"],
      ["query-optimization", "Query Optimization"],
      ["partitioning", "Partitioning"],
      ["replication", "Replication"],
      ["security", "SQL Security"],
      ["analytics", "Analytics Queries"],
    ],
    "04-professional": [
      ["postgresql", "PostgreSQL"],
      ["mysql", "MySQL"],
      ["mssql", "SQL Server"],
      ["etl", "ETL Pipelines"],
      ["data-warehousing", "Data Warehousing"],
      ["db-admin", "Database Administration"],
    ],
    "05-mastery": [
      ["performance-tuning", "Performance Tuning"],
      ["distributed-sql", "Distributed SQL"],
      ["capstone-projects", "Capstone Projects"],
      ["dba-career", "DBA Career Path"],
    ],
  },
  Powershell: {
    "01-beginner": [
      ["introduction", "Introduction to PowerShell"],
      ["powershell-basics", "PowerShell Basics"],
      ["hello-world", "Hello World"],
      ["variables", "Variables"],
      ["control-flow", "Control Flow"],
      ["functions", "Functions"],
      ["pipelines", "Pipelines"],
      ["objects", "Objects in PowerShell"],
      ["file-system", "File System Cmdlets"],
      ["help-system", "Help System"],
    ],
    "02-intermediate": [
      ["modules", "Modules"],
      ["remoting", "Remoting"],
      ["error-handling", "Error Handling"],
      ["scripting", "Scripting Best Practices"],
      ["regex", "Regular Expressions"],
      ["jobs", "Background Jobs"],
    ],
    "03-advanced": [
      ["desired-state", "Desired State Configuration"],
      ["classes", "PowerShell Classes"],
      ["api-integration", "API Integration"],
      ["security", "Security"],
      ["performance", "Performance"],
      ["testing-pester", "Pester Testing"],
      ["automation", "Automation Patterns"],
    ],
    "04-professional": [
      ["azure-automation", "Azure Automation"],
      ["active-directory", "Active Directory"],
      ["exchange", "Exchange Administration"],
      ["devops", "DevOps with PowerShell"],
      ["reporting", "Reporting"],
      ["enterprise", "Enterprise Scripting"],
    ],
    "05-mastery": [
      ["advanced-automation", "Advanced Automation"],
      ["tool-building", "Building Tools"],
      ["capstone-projects", "Capstone Projects"],
      ["career-path", "Career Path"],
    ],
  },
  Batchfile: {
    "01-beginner": [
      ["introduction", "Introduction to Batch Scripts"],
      ["batch-basics", "Batch Basics"],
      ["hello-world", "Hello World"],
      ["variables", "Variables"],
      ["control-flow", "Control Flow"],
      ["functions", "Functions and Labels"],
      ["file-operations", "File Operations"],
      ["loops", "Loops"],
      ["input-output", "Input and Output"],
      ["error-handling", "Error Handling"],
    ],
    "02-intermediate": [
      ["advanced-scripting", "Advanced Scripting"],
      ["admin-tasks", "Administration Tasks"],
      ["scheduling", "Task Scheduling"],
      ["networking", "Networking Commands"],
      ["logging", "Logging"],
      ["security", "Script Security"],
    ],
    "03-advanced": [
      ["powershell-integration", "PowerShell Integration"],
      ["wmi", "WMI Queries"],
      ["registry", "Registry Operations"],
      ["deployment", "Deployment Scripts"],
      ["troubleshooting", "Troubleshooting"],
      ["best-practices", "Best Practices"],
      ["cross-platform", "Cross-Platform Notes"],
    ],
    "04-professional": [
      ["enterprise", "Enterprise Automation"],
      ["ci-cd", "CI/CD Integration"],
      ["monitoring", "Monitoring Scripts"],
      ["backup", "Backup Automation"],
      ["documentation", "Documentation"],
      ["team-standards", "Team Standards"],
    ],
    "05-mastery": [
      ["complex-automation", "Complex Automation"],
      ["capstone-projects", "Capstone Projects"],
      ["migration", "Migration Scripts"],
      ["career-notes", "IT Career Notes"],
    ],
  },
};

/** JavaScript-only extra lessons (added without overwriting existing) */
const JS_EXTRA_LESSONS = {
  "01-beginner": [
    ["09-strings-and-template-literals", "Strings and Template Literals"],
    ["10-debugging-and-devtools", "Debugging and DevTools"],
  ],
  "02-intermediate": [
    ["06-fetch-api", "Fetch API"],
    ["07-json-and-apis", "JSON and REST APIs"],
  ],
};

module.exports = {
  MODULES,
  CERT_LESSONS,
  LANGUAGE_LESSONS,
  JS_EXTRA_LESSONS,
};
